What is ColumnTransformer?

The ColumnTransformer is a class in the scikit-learn Python machine learning library that allows you to selectively apply data preparation transforms to different columns in your dataset. This is particularly useful when you have a mix of numerical and categorical data that require different preprocessing steps.

Why Use ColumnTransformer?

Using ColumnTransformer offers several advantages:

Selective Transformation: Apply specific transformations to subsets of columns.
Pipeline Integration: Easily integrate with scikit-learn's Pipeline for streamlined workflows.
Code Organization: Encapsulate preprocessing logic in a single, maintainable object.

In [1]:
# import the required libraries
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [6]:
# reading the dataset which is attached at end.
df = pd.read_csv('Car_Speed_Data.csv')
df.head()

   Age  Gender  Speed Average_speed     City has_driving_license
0   54    male   40.0           low  Kolkata                 yes
1   34  female   70.0           low    Delhi                 yes
2   19  female  140.0          high   Delhi                   no
3   45    male  120.0          high  Kolkata                 yes
4   23   male    80.0           low   Mumbai                  no

In [7]:
df.isnull().sum()

Age                    0
Gender                 0
Speed                  9
Average_speed          0
City                   0
has_driving_license    0
dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_driving_license']),df['has_driving_license'],
                                                test_size=0.2)
X_train

    Age  Gender  Speed Average_speed      City
82   51  female  170.0          high    Mumbai
36   36    male   50.0           low   Kolkata
0    54    male   40.0           low   Kolkata
71   43  female   70.0           low   Kolkata
84   46  female   50.0           low     Delhi
..  ...     ...    ...           ...       ...
19   25  female  130.0          high  Banglore
64   28  female  180.0          high    Mumbai
25   35    male  100.0          high  Banglore
86   34    male   60.0           low  Banglore
30   41    male   50.0           low  Banglore

[80 rows x 5 columns]

In [9]:
# we are using SimpleInputer() for speed Column
si = SimpleImputer()
X_train_Speed = si.fit_transform(X_train[['Speed']])

#for test data
X_test_Speed = si.fit_transform(X_test[['Speed']])

X_train_Speed.shape
#to check whether values or replaced by mean or not you simply call X_train_speed function
#output: (80,1)

(80, 1)

In [10]:
# Ordinalencoding for Average_speed
oe = OrdinalEncoder(categories=[['low','high']])
X_train_Average_speed = oe.fit_transform(X_train[['Average_speed']])

# for test data
X_test_Average_speed = oe.fit_transform(X_test[['Average_speed']])

X_train_Average_speed.shape
#output (80,1)
#you can also check it by calling the function X_train_Average_speed

(80, 1)

In [12]:
# Performing OneHotEncoding for Gender,City
ohe = OneHotEncoder(drop='first', sparse_output=False)
X_train_Gender_City = ohe.fit_transform(X_train[['Gender','City']])

#For test data
X_test_Gender_City = ohe.transform(X_test[['Gender','City']])

X_train_Gender_City.shape
#output:(80,7)
#you can call X_train_Gender_City for checking the feature values.

(80, 7)

In [13]:
# Extracting Age
X_train_age = X_train.drop(columns=['Gender','Speed','Average_speed','City']).values

# for test data
X_test_age = X_test.drop(columns=['Gender','Speed','Average_speed','City']).values

X_train_age.shape
#output: (80,1)

(80, 1)

In [14]:
#using np.concatenate which combines multiple arrays along a specified axis. Here, axis=1 ensures that the arrays are joined horizontally
X_train_transformed = np.concatenate((X_train_age,X_train_Speed,X_train_Gender_City,X_train_Average_speed),axis=1)
#for test data
X_test_transformed = np.concatenate((X_test_age,X_test_Speed,X_test_Gender_City,X_test_Average_speed),axis=1)

X_train_transformed.shape

#output: (80,10)
#the output includes 80 samples and 10 total features (including encoded and numerical) shape.

(80, 10)

In [17]:
from sklearn.compose import ColumnTransformer
# we have declared transformer and called ColumnTransformer() method
#we use SimpleImputer for speed and t1 as parameter,t2 for OrdinalEncoder i.e for categorical values and t3 for one hot encoding i.e for Gender and City.
transformer = ColumnTransformer(transformers=[
    ('t1',SimpleImputer(),['Speed']),
    ('t2',OrdinalEncoder(categories=[['low','high']]),['Average_speed']),
    ('t3',OneHotEncoder(sparse_output=False,drop='first'),['Gender','City'])
],remainder='passthrough')

In [20]:
transformer.fit_transform(X_train).shape
#output:(80,10)
transformer.transform(X_test).shape
#output: (20,10)

(20, 10)

In [19]:
print(transformer.transform(X_test))

[[ 70.           0.           1.           0.           0.
    0.           0.           0.           0.          42.        ]
 [150.           1.           0.           0.           0.
    1.           0.           0.           0.          27.        ]
 [ 90.           0.           1.           0.           0.
    0.           0.           0.           1.          32.        ]
 [ 50.           0.           1.           0.           0.
    0.           0.           1.           0.          34.        ]
 [120.           1.           1.           0.           0.
    0.           0.           1.           0.          27.        ]
 [ 70.           0.           0.           0.           0.
    1.           0.           0.           0.          39.        ]
 [140.           1.           1.           0.           0.
    0.           0.           0.           1.          51.        ]
 [ 50.           0.           0.           0.           0.
    0.           0.           0.           0.          24.        ]
 [ 95.75342466   0.           0.           0.           0.
    0.           0.           0.           1.          29.        ]
 [ 40.           0.           0.           0.           0.
    0.           0.           1.           0.          36.        ]
 [ 60.           0.           1.           0.           0.
    0.           0.           0.           1.          29.        ]
 [ 60.           0.           0.           0.           0.
    0.           0.           0.           1.          34.        ]
 [ 90.           0.           0.           0.           0.
    0.           0.           1.           0.          28.        ]
 [ 70.           0.           0.           0.           0.
    1.           0.           0.           0.          23.        ]
 [ 95.75342466   1.           0.           0.           0.
    0.           0.           0.           0.          24.        ]
 [ 50.           0.           0.           0.           0.
    1.           0.           0.           0.          28.        ]
 [ 80.           0.           1.           0.           0.
    1.           0.           0.           0.          56.        ]
 [ 50.           0.           0.           0.           0.
    0.           0.           0.           1.          40.        ]
 [120.           1.           1.           0.           0.
    1.           0.           0.           0.          47.        ]
 [120.           1.           1.           0.           0.
    0.           0.           0.           0.          52.        ]]