In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('/content/CAR DETAILS FROM CAR DEKHO.csv')

In [3]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

In [6]:
df=df[['selling_price','km_driven','year']]
df

      selling_price  km_driven  year
0             60000      70000  2007
1            135000      50000  2007
2            600000     100000  2012
3            250000      46000  2017
4            450000     141000  2014
...             ...        ...   ...
4335         409999      80000  2014
4336         409999      80000  2014
4337         110000      83000  2009
4338         865000      90000  2016
4339         225000      40000  2016

[4340 rows x 3 columns]

**Applaying Normalization=MinMax Scaling**

In [7]:
from sklearn.preprocessing import MinMaxScaler

In [8]:
scalar=MinMaxScaler()

In [9]:
scalar.fit_transform(df[['selling_price','km_driven','year']])

array([[0.0045045 , 0.08678301, 0.53571429],
       [0.01295045, 0.06198751, 0.53571429],
       [0.06531532, 0.12397626, 0.71428571],
       ...,
       [0.01013514, 0.10290008, 0.60714286],
       [0.09515766, 0.11157851, 0.85714286],
       [0.02308559, 0.04958976, 0.85714286]])

In [10]:
new_df=pd.DataFrame(scalar.fit_transform(df[['selling_price','km_driven','year']]),columns=['selling_price','km_driven','year'])

In [11]:
new_df

      selling_price  km_driven      year
0          0.004505   0.086783  0.535714
1          0.012950   0.061988  0.535714
2          0.065315   0.123976  0.714286
3          0.025901   0.057028  0.892857
4          0.048423   0.174807  0.785714
...             ...        ...       ...
4335       0.043919   0.099181  0.785714
4336       0.043919   0.099181  0.785714
4337       0.010135   0.102900  0.607143
4338       0.095158   0.111579  0.857143
4339       0.023086   0.049590  0.857143

[4340 rows x 3 columns]

***Train-Test split***

In [15]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test=train_test_split(new_df.drop('selling_price',axis=1),new_df['selling_price'],test_size=0.2,random_state=42)

***Feature-Scalling :mormalization minmaxscalar***

In [16]:
X_train_scaled=scalar.fit_transform(x_train)
X_test_scaled=scalar.transform(x_test)

When should you use MinMaxScaler?

It's especially useful when your ML algorithm is sensitive to the scale of features.

Good cases:

KNN ⭐⭐⭐⭐⭐

K-Means clustering ⭐⭐⭐⭐⭐

Neural Networks ⭐⭐⭐⭐⭐

SVM ⭐⭐⭐⭐

Gradient Descent-based models ⭐⭐⭐⭐

PCA can also benefit from scaling.

For example, in KNN:

Distance = √((Age difference)² + (Salary difference)²)

Because salary has much larger numbers, it can dominate the distance.

After normalization, both features have comparable scales.

2. Example with KNN

Suppose we want to find which student is closest to a new student.

New student:

Age = 24
Salary = 45,000

Student A:

Age = 20
Salary = 20,000

Euclidean distance:

$$ Distance = \sqrt{(24-20)^2 + (45000-20000)^2} $$

So:

$$ = \sqrt{4^2 + 25000^2} $$

The salary difference is 25,000, while the age difference is only 4.

Therefore, salary dominates the distance.

This can be a problem because the algorithm doesn't know that salary is "more important" just because its numerical values are larger.